### ISSUE TITLE
Slow execution time

### ISSUE THREAD

**Issue by ChrGri** [schnoog/Joystick_ESP32S2#1]
Hi @schnoog, 
thank you for the port. Good job. It works as expected. I wrote a simple script to measure the runtime.
With Arduino Due and the original lib, 36µs have been timed. With an ESP32 S2, approx. 1000µs have been timed for the same script, see attachment.

Is it possible to achieve similar runtimes on ESP32?

BR

----EDIT-----
I've added an zero here, now it runs at 20µs on the ESP:
![image](https://github.com/schnoog/Joystick_ESP32S2/assets/21274895/07e2d824-5a25-41ea-a7af-8800cd5b2f8c)

[DrivingControllerTest_Profiling.zip](https://github.com/schnoog/Joystick_ESP32S2/files/11470824/DrivingControllerTest_Profiling.zip)

**Comment by schnoog** [comment]
Thank you very much for your feedback (and providing the solution).

Will change it in the library and after testing issue a new version.
