### ISSUE TITLE
Mux over i2c

### ISSUE THREAD

**Issue by team-ajas** [schnoog/Joystick_ESP32S2#10]
Hello, first of all thanks for the work, I am trying to add an mcp23017 mutiplexer via i2c but I cannot get the communication between it and esp32s3. The information I have found does not take me anywhere. Would you know how to configure the gpio's for this purpose, thank you

**Comment by schnoog** [comment]
Hi, 
first sorry for the very late reply. Somehow missed the Github mail about it.
I'm using MCP23017 in conjunction with the library and an ESP32-S3 without problems.

However, I also struggled with some I2C devices at the beginning. I tried several pin combinations until it worked with the board default I2C pin settings.
