### ISSUE TITLE
Buttons as dpad using hat instead of axis

### ISSUE THREAD

**Issue by hersa37** [schnoog/Joystick_ESP32S2#15]
I'm having a bit of trouble trying to setup directional buttons as a dpad. Using the buttons as X and Y axis works, especially for diagonals, but using them as hat is a bit hard considering I have to make a case for every diagonal. Is there an easier way to make them work as dpad?

**Comment by schnoog** [comment]
Hi,
unfortunately I'm not aware of an easier method.
Maybe the example
https://github.com/schnoog/Joystick_ESP32S2/blob/main/examples/HatSwitchTest/HatSwitchTest.ino
if helpful for your purpose.
