### ISSUE TITLE
Joystick not recognized

### ISSUE THREAD

**Issue by hfjg** [schnoog/Joystick_ESP32S2#2]
# Issue
Examples "FlightControllerTest.ino" and "JoystickTest.ino" both do not report HID device. Actually, nothing is reported.
Test with flashing the onboard LED works, so I expect the program is transferred correctly.

## Hardware
S2_DevBoard-clone  by "VCC GND", separate usb connectors for native usb and UART

## PC
* Linux Mint (feat. Ubuntu 20.3)
* Platformio w/ Arduino framework

Examples checked with lsusb, dmesg and syslog, no USB from board reported

**Comment by schnoog** [comment]
Hi,
I tries the examples on a S2 and a S3 board. Before i pushed them to github.
Using the Arduino IDE it's necessary to 
"enable USB CDC on boot".
Additionally I have chosen the USB-Mode USB-OTG(TinyUSB)

Unfortunately I'm currently not aware how to set this in Platfromio.

**Comment by hfjg** [comment]
Thank you. I'll check tomorrow.

**Comment by schnoog** [comment]
You're welcome.

`build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1`

in your platformio.ini should do the trick.

**Comment by schnoog** [comment]
Great to hear that.
Thank you very much for your feedback
